In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
books = pd.read_csv('books.csv')
books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [3]:
books.shape

(10000, 23)

In [4]:
books.columns

Index(['id', 'book_id', 'best_book_id', 'work_id', 'books_count', 'isbn',
       'isbn13', 'authors', 'original_publication_year', 'original_title',
       'title', 'language_code', 'average_rating', 'ratings_count',
       'work_ratings_count', 'work_text_reviews_count', 'ratings_1',
       'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5', 'image_url',
       'small_image_url'],
      dtype='object')

In [5]:
books.drop(['id','best_book_id','work_id','isbn',
       'isbn13','work_ratings_count', 'work_text_reviews_count', 'ratings_1',
       'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5', 'books_count'],axis=1,inplace=True)

In [6]:
books = books.dropna()

In [7]:
books = books.sort_values(by='book_id')

In [8]:
books.reset_index(inplace=True)

In [9]:
books.drop(['index'],inplace=True,axis=1)

In [10]:
books["ratings_count"] = np.sqrt(books.ratings_count/books.ratings_count.sum())

In [11]:
books

,book_id,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,image_url,small_image_url
0,1,"J.K. Rowling, Mary GrandPré",2005.0,Harry Potter and the Half-Blood Prince,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,0.058035,https://images.gr-assets.com/books/1361039191m...,https://images.gr-assets.com/books/1361039191s...
1,2,"J.K. Rowling, Mary GrandPré",2003.0,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix (Har...,eng,4.46,0.059004,https://images.gr-assets.com/books/1387141547m...,https://images.gr-assets.com/books/1387141547s...
2,3,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,0.096092,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
3,5,"J.K. Rowling, Mary GrandPré, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...,eng,4.53,0.060639,https://images.gr-assets.com/books/1499277281m...,https://images.gr-assets.com/books/1499277281s...
4,6,"J.K. Rowling, Mary GrandPré",2000.0,Harry Potter and the Goblet of Fire,Harry Potter and the Goblet of Fire (Harry Pot...,eng,4.53,0.059304,https://images.gr-assets.com/books/1361482611m...,https://images.gr-assets.com/books/1361482611s...
...,...,...,...,...,...,...,...,...,...,...
8400,31538635,"J.K. Rowling, MinaLima",2016.0,"Short Stories from Hogwarts of Heroism, Hardsh...","Short Stories from Hogwarts of Heroism, Hardsh...",eng,4.22,0.005716,https://images.gr-assets.com/books/1471436733m...,https://images.gr-assets.com/books/1471436733s...
8401,31538647,J.K. Rowling,2016.0,Hogwarts: An Incomplete and Unreliable Guide,Hogwarts: An Incomplete and Unreliable Guide (...,eng,4.21,0.005482,https://images.gr-assets.com/books/1502156557m...,https://images.gr-assets.com/books/1502156557s...
8402,31845516,Glennon Doyle Melton,2016.0,Love Warrior,Love Warrior,en-US,4.10,0.006349,https://images.gr-assets.com/books/1473164102m...,https://images.gr-assets.com/books/1473164102s...
8403,32075671,Angie Thomas,2017.0,The Hate U Give,The Hate U Give,eng,4.62,0.008088,https://images.gr-assets.com/books/1476284759m...,https://images.gr-assets.com/books/1476284759s...
8404,33288638,Mariana Zapata,2016.0,Wait for It,Wait for It,eng,4.22,0.006071,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...

In [13]:
books_tags = pd.read_csv('book_tags.csv')
books_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [14]:
books_tags = books_tags.rename(columns={"goodreads_book_id":"book_id"})

In [15]:
books_tags

         book_id  tag_id   count
0              1   30574  167697
1              1   11305   37174
2              1   11557   34173
3              1    8717   12986
4              1   33114   12716
...          ...     ...     ...
999907  33288638   21303       7
999908  33288638   17271       7
999909  33288638    1126       7
999910  33288638   11478       7
999911  33288638   27939       7

[999912 rows x 3 columns]

In [16]:
tags = pd.read_csv('tags.csv')
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

### Merging the dataframes

Merge books_tags, tags on tag_id

In [17]:
tags_merge = books_tags.merge(tags,left_on="tag_id",right_on="tag_id",how='inner')

Merge tags with books
on book_id

In [18]:
final_df = books.merge(tags_merge,left_on="book_id",right_on = "book_id",how="inner")

In [19]:
final_df.drop(['tag_id','count'],axis=1,inplace=True)

In [20]:
final_df.shape

(840462, 9)

In [21]:
final_df.columns

Index(['book_id', 'authors', 'original_publication_year', 'original_title',
       'title', 'language_code', 'average_rating', 'ratings_count',
       'tag_name'],
      dtype='object')

In [12]:
books

,book_id,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,image_url,small_image_url
0,1,"J.K. Rowling, Mary GrandPré",2005.0,Harry Potter and the Half-Blood Prince,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,0.058035,https://images.gr-assets.com/books/1361039191m...,https://images.gr-assets.com/books/1361039191s...
1,2,"J.K. Rowling, Mary GrandPré",2003.0,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix (Har...,eng,4.46,0.059004,https://images.gr-assets.com/books/1387141547m...,https://images.gr-assets.com/books/1387141547s...
2,3,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,0.096092,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
3,5,"J.K. Rowling, Mary GrandPré, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...,eng,4.53,0.060639,https://images.gr-assets.com/books/1499277281m...,https://images.gr-assets.com/books/1499277281s...
4,6,"J.K. Rowling, Mary GrandPré",2000.0,Harry Potter and the Goblet of Fire,Harry Potter and the Goblet of Fire (Harry Pot...,eng,4.53,0.059304,https://images.gr-assets.com/books/1361482611m...,https://images.gr-assets.com/books/1361482611s...
...,...,...,...,...,...,...,...,...,...,...
8400,31538635,"J.K. Rowling, MinaLima",2016.0,"Short Stories from Hogwarts of Heroism, Hardsh...","Short Stories from Hogwarts of Heroism, Hardsh...",eng,4.22,0.005716,https://images.gr-assets.com/books/1471436733m...,https://images.gr-assets.com/books/1471436733s...
8401,31538647,J.K. Rowling,2016.0,Hogwarts: An Incomplete and Unreliable Guide,Hogwarts: An Incomplete and Unreliable Guide (...,eng,4.21,0.005482,https://images.gr-assets.com/books/1502156557m...,https://images.gr-assets.com/books/1502156557s...
8402,31845516,Glennon Doyle Melton,2016.0,Love Warrior,Love Warrior,en-US,4.10,0.006349,https://images.gr-assets.com/books/1473164102m...,https://images.gr-assets.com/books/1473164102s...
8403,32075671,Angie Thomas,2017.0,The Hate U Give,The Hate U Give,eng,4.62,0.008088,https://images.gr-assets.com/books/1476284759m...,https://images.gr-assets.com/books/1476284759s...
8404,33288638,Mariana Zapata,2016.0,Wait for It,Wait for It,eng,4.22,0.006071,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...

### Computing cosine-similarity using authors, publication year, title, Language_code, average rating, ratings_count and tag_name

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from scipy.sparse import coo_matrix, hstack

In [14]:
f = (pd.Series(books[['authors','title']]
                .fillna('')
                .values.tolist()
                ).str.join(' '))

In [15]:
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(f.astype('U'))

In [16]:
#tfidf_matrix = hstack([tfidf_matrix,np.array(final_df['average_rating'].values[:2000]).reshape(-1,1)])

In [17]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [18]:
cosine_sim

array([[1.        , 0.67046347, 0.67482699, ..., 0.        , 0.        ,
        0.        ],
       [0.67046347, 1.        , 0.69353451, ..., 0.        , 0.        ,
        0.        ],
       [0.67482699, 0.69353451, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [89]:
titles = books['original_title']
indices = pd.Series(books.index, index=books['title'])

# Function that get book recommendations based on the cosine similarity score of book authors
def authors_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:21]
    book_indices = [i[0] for i in sim_scores]
    rec = []
    for j in book_indices:
        dic = {}
        dic["title"] = books['title'].iloc[j]
        dic["img"] = books['image_url'].iloc[j]
        dic["year"] = books['original_publication_year'].iloc[j]
        dic["rating"] = books['average_rating'].iloc[j]
        dic["author"] = books['authors'].iloc[j].replace('  ','') 
        rec.append(dic)
#     print(rec)
#     img_urls = [books['image_url'].iloc[i] for i in book_indices]
#     year = [books['original_publication_year'].iloc[i] for i in book_indices]
#     rating = [books['average_rating'].iloc[i] for i in book_indices]
#     authors = [books['authors'].iloc[i].replace('  ','') for i in book_indices]
    return rec

In [90]:
authors_recommendations("Romeo and Juliet")

[{'title': 'The Merchant of Venice',
  'img': 'https://images.gr-assets.com/books/1327871054m/24128.jpg',
  'year': 1596.0,
  'rating': 3.78,
  'author': 'William Shakespeare, RobertJackson, Barbara A. Mowat, Paul Werstine'},
 {'title': 'As You Like It',
  'img': 'https://images.gr-assets.com/books/1327935363m/42607.jpg',
  'year': 1599.0,
  'rating': 3.83,
  'author': 'William Shakespeare'},
 {'title': 'Macbeth',
  'img': 'https://images.gr-assets.com/books/1459795224m/8852.jpg',
  'year': 1606.0,
  'rating': 3.88,
  'author': 'William Shakespeare'},
 {'title': 'Othello',
  'img': 'https://images.gr-assets.com/books/1459795105m/12996.jpg',
  'year': 1603.0,
  'rating': 3.88,
  'author': 'William Shakespeare'},
 {'title': 'The Tempest',
  'img': 'https://images.gr-assets.com/books/1327793692m/12985.jpg',
  'year': 1623.0,
  'rating': 3.8,
  'author': 'William Shakespeare'},
 {'title': 'Much Ado About Nothing',
  'img': 'https://images.gr-assets.com/books/1327885569m/12957.jpg',
  'year': 1598.0,
  'rating': 4.06,
  'author': 'William Shakespeare, Barbara A. Mowat, Paul Werstine, Gail Kern Paster, RobertJackson'},
 {'title': "The Winter's Tale",
  'img': 'https://images.gr-assets.com/books/1327893509m/44133.jpg',
  'year': 1600.0,
  'rating': 3.69,
  'author': 'William Shakespeare'},
 {'title': 'King Lear',
  'img': 'https://images.gr-assets.com/books/1331563731m/12938.jpg',
  'year': 1603.0,
  'rating': 3.89,
  'author': 'William Shakespeare'},
 {'title': 'The Complete Works',
  'img': 'https://images.gr-assets.com/books/1327884293m/569564.jpg',
  'year': 1623.0,
  'rating': 4.49,
  'author': 'William Shakespeare'},
 {'title': 'Twelfth Night',
  'img': 'https://images.gr-assets.com/books/1416628008m/1625.jpg',
  'year': 1601.0,
  'rating': 3.97,
  'author': 'William Shakespeare'},
 {'title': 'The Taming of the Shrew',
  'img': 'https://images.gr-assets.com/books/1327935253m/47021.jpg',
  'year': 1593.0,
  'rating': 3.81,
  'author': 'William Shakespeare'},
 {'title': "Shakespeare's Sonnets",
  'img': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
  'year': 1592.0,
  'rating': 4.24,
  'author': 'William Shakespeare, Katherine Duncan-Jones'},
 {'title': "William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars, #4)",
  'img': 'https://images.gr-assets.com/books/1411696453m/17262540.jpg',
  'year': 2013.0,
  'rating': 3.94,
  'author': 'Ian Doescher'},
 {'title': 'City of Stairs (The Divine Cities, #1)',
  'img': 'https://images.gr-assets.com/books/1394545220m/20174424.jpg',
  'year': 2014.0,
  'rating': 4.13,
  'author': 'Robert Jackson Bennett'},
 {'title': 'Henry V',
  'img': 'https://images.gr-assets.com/books/1331563646m/37526.jpg',
  'year': 1599.0,
  'rating': 3.87,
  'author': 'William Shakespeare, Barbara A. Mowat, Paul Werstine'},
 {'title': 'Julius Caesar',
  'img': 'https://images.gr-assets.com/books/1354574927m/13006.jpg',
  'year': 1599.0,
  'rating': 3.65,
  'author': 'William Shakespeare, Roma Gill'},
 {'title': 'Hamlet',
  'img': 'https://images.gr-assets.com/books/1351051208m/1420.jpg',
  'year': 1600.0,
  'rating': 4.0,
  'author': 'William Shakespeare, Richard Andrews, Rex Gibson'},
 {'title': 'Measure for Measure',
  'img': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
  'year': 1603.0,
  'rating': 3.67,
  'author': 'William Shakespeare, Barbara A. Mowat, Paul Werstine'},
 {'title': 'King Henry IV, Part 1 (Wars of the Roses, #2)',
  'img': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
  'year': 1597.0,
  'rating': 3.81,
  'author': 'William Shakespeare, David Scott Kastan'},
 {'title': 'Antony and Cleopatra',
  'img': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
  'year': 1606.0,
  'rating': 3.67,
  'author': 'William Shakespeare, Cynthia Marshall, Barbara A. Mowat, Paul Werstine'}]

In [30]:
from numpy import asarray
from numpy import savetxt
# define data
# save to csv file
savetxt('cosinesim.csv', cosine_sim , delimiter=',')

In [59]:
books.to_csv('books1.csv',index=False)

In [199]:
# load numpy array from csv file
from numpy import loadtxt
# load array
data = loadtxt('cosinesim.csv', delimiter=',')

In [37]:
data = np.fromfile('cosinesim.csv', sep=',')

<ipython-input-37-4604717a3615>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  data = np.fromfile('cosinesim.csv', sep=',')

In [38]:
cosine_sim

array([[1.        , 0.67046347, 0.67482699, ..., 0.        , 0.        ,
        0.        ],
       [0.67046347, 1.        , 0.69353451, ..., 0.        , 0.        ,
        0.        ],
       [0.67482699, 0.69353451, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [35]:
data

array([1.        , 0.67046347, 0.67482699, ..., 0.        , 0.        ,
       0.        ])

In [204]:
def authors_recommendations(title,cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:21]
    book_indices = [i[0] for i in sim_scores]
    return titles.iloc[book_indices]

In [1]:
authors_recommendations("Romeo and Juliet",data)

NameError: name 'authors_recommendations' is not defined

In [ ]:
data = numpy.fromfile('./allpoints.txt', dtype=float, count=-1, sep=' ')

In [229]:
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings
  
warnings.filterwarnings(action = 'ignore')
  
import gensim
from gensim.models import Word2Vec,KeyedVectors
from gensim import models

In [218]:
model1 = gensim.models.Word2Vec(f.astype('U'), min_count = 1)

In [ ]:
vocabulary = word2vec.wv.vocab

In [230]:
from gensim import models
w = models.Word2Vec.load_word2vec_format(books['titles'].values, binary=True)

AttributeError: type object 'Word2Vec' has no attribute 'load_word2vec_format'

In [231]:
games = pd.read_csv('steam-200k.csv')

In [232]:
games.head()

   151603712  The Elder Scrolls V Skyrim  purchase    1.0  0
0  151603712  The Elder Scrolls V Skyrim      play  273.0  0
1  151603712                   Fallout 4  purchase    1.0  0
2  151603712                   Fallout 4      play   87.0  0
3  151603712                       Spore  purchase    1.0  0
4  151603712                       Spore      play   14.9  0

In [233]:
games = games.rename(columns={"The Elder Scrolls V Skyrim":"name"})

In [234]:
game = games['name']

In [238]:
game = game.drop_duplicates()

In [240]:
game

0                  The Elder Scrolls V Skyrim
1                                   Fallout 4
3                                       Spore
5                           Fallout New Vegas
7                               Left 4 Dead 2
                         ...
198737                     Warriors & Castles
199021    Romance of the Three Kingdoms Maker
199582                           Space Colony
199660                           Life is Hard
199664                      Executive Assault
Name: name, Length: 5155, dtype: object

In [242]:
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(game.astype('U'))

In [243]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [244]:
titles = game
indices = pd.Series(game.index, index=game)

# Function that get book recommendations based on the cosine similarity score of book authors
def authors_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:21]
    book_indices = [i[0] for i in sim_scores]
    return titles.iloc[book_indices]

In [44]:
b = pd.read_csv('books.csv')

In [48]:
b["title"].values

array(['The Hunger Games (The Hunger Games, #1)',
       "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",
       'Twilight (Twilight, #1)', ..., 'The Mauritius Command',
       'Cinderella Ate My Daughter: Dispatches from the Frontlines of the New Girlie-Girl Culture',
       'The First World War'], dtype=object)